<?php

return [
    'AF' => '🇦🇫 Afghanistan',
    'AL' => '🇦🇱 Albania',
    'DZ' => '🇩🇿 Algeria',
    'AS' => '🇦🇸 American Samoa',
    'AD' => '🇦🇩 Andorra',
    'AO' => '🇦🇴 Angola',
    'AI' => '🇦🇮 Anguilla',
    'AQ' => '🇦🇶 Antarctica',
    'AG' => '🇦🇬 Antigua and Barbuda',
    'AR' => '🇦🇷 Argentina',
    'AM' => '🇦🇲 Armenia',
    'AW' => '🇦🇼 Aruba',
    'AU' => '🇦🇺 Australia',
    'AT' => '🇦🇹 Austria',
    'AZ' => '🇦🇿 Azerbaijan',

    'BS' => '🇧🇸 Bahamas',
    'BH' => '🇧🇭 Bahrain',
    'BD' => '🇧🇩 Bangladesh',
    'BB' => '🇧🇧 Barbados',
    'BY' => '🇧🇾 Belarus',
    'BE' => '🇧🇪 Belgium',
    'BZ' => '🇧🇿 Belize',
    'BJ' => '🇧🇯 Benin',
    'BM' => '🇧🇲 Bermuda',
    'BT' => '🇧🇹 Bhutan',
    'BO' => '🇧🇴 Bolivia',
    'BA' => '🇧🇦 Bosnia and Herzegovina',
    'BW' => '🇧🇼 Botswana',
    'BR' => '🇧🇷 Brazil',
    'BN' => '🇧🇳 Brunei',
    'BG' => '🇧🇬 Bulgaria',
    'BF' => '🇧🇫 Burkina Faso',
    'BI' => '🇧🇮 Burundi',

    'KH' => '🇰🇭 Cambodia',
    'CM' => '🇨🇲 Cameroon',
    'CA' => '🇨🇦 Canada',
    'CV' => '🇨🇻 Cape Verde',
    'KY' => '🇰🇾 Cayman Islands',
    'CF' => '🇨🇫 Central African Republic',
    'TD' => '🇹🇩 Chad',
    'CL' => '🇨🇱 Chile',
    'CN' => '🇨🇳 China',
    'CO' => '🇨🇴 Colombia',
    'KM' => '🇰🇲 Comoros',
    'CG' => '🇨🇬 Congo',
    'CR' => '🇨🇷 Costa Rica',
    'HR' => '🇭🇷 Croatia',
    'CU' => '🇨🇺 Cuba',
    'CY' => '🇨🇾 Cyprus',
    'CZ' => '🇨🇿 Czech Republic',

    'DK' => '🇩🇰 Denmark',
    'DJ' => '🇩🇯 Djibouti',
    'DM' => '🇩🇲 Dominica',
    'DO' => '🇩🇴 Dominican Republic',

    'EC' => '🇪🇨 Ecuador',
    'EG' => '🇪🇬 Egypt',
    'SV' => '🇸🇻 El Salvador',
    'EE' => '🇪🇪 Estonia',
    'ET' => '🇪🇹 Ethiopia',

    'FJ' => '🇫🇯 Fiji',
    'FI' => '🇫🇮 Finland',
    'FR' => '🇫🇷 France',

    'GA' => '🇬🇦 Gabon',
    'GM' => '🇬🇲 Gambia',
    'GE' => '🇬🇪 Georgia',
    'DE' => '🇩🇪 Germany',
    'GH' => '🇬🇭 Ghana',
    'GR' => '🇬🇷 Greece',
    'GD' => '🇬🇩 Grenada',
    'GT' => '🇬🇹 Guatemala',

    'HT' => '🇭🇹 Haiti',
    'HN' => '🇭🇳 Honduras',
    'HK' => '🇭🇰 Hong Kong',
    'HU' => '🇭🇺 Hungary',

    'IS' => '🇮🇸 Iceland',
    'IN' => '🇮🇳 India',
    'ID' => '🇮🇩 Indonesia',
    'IR' => '🇮🇷 Iran',
    'IE' => '🇮🇪 Ireland',
    'IL' => '🇮🇱 Israel',
    'IT' => '🇮🇹 Italy',

    'JM' => '🇯🇲 Jamaica',
    'JP' => '🇯🇵 Japan',
    'JO' => '🇯🇴 Jordan',

    'KZ' => '🇰🇿 Kazakhstan',
    'KE' => '🇰🇪 Kenya',
    'KW' => '🇰🇼 Kuwait',

    'LA' => '🇱🇦 Laos',
    'LV' => '🇱🇻 Latvia',
    'LB' => '🇱🇧 Lebanon',
    'LS' => '🇱🇸 Lesotho',
    'LY' => '🇱🇾 Libya',
    'LI' => '🇱🇮 Liechtenstein',
    'LT' => '🇱🇹 Lithuania',
    'LU' => '🇱🇺 Luxembourg',

    'MY' => '🇲🇾 Malaysia',
    'MV' => '🇲🇻 Maldives',
    'MT' => '🇲🇹 Malta',
    'MX' => '🇲🇽 Mexico',
    'MD' => '🇲🇩 Moldova',
    'MC' => '🇲🇨 Monaco',
    'MN' => '🇲🇳 Mongolia',
    'ME' => '🇲🇪 Montenegro',
    'MA' => '🇲🇦 Morocco',

    'NA' => '🇳🇦 Namibia',
    'NP' => '🇳🇵 Nepal',
    'NL' => '🇳🇱 Netherlands',
    'NZ' => '🇳🇿 New Zealand',
    'NI' => '🇳🇮 Nicaragua',
    'NG' => '🇳🇬 Nigeria',
    'NO' => '🇳🇴 Norway',

    'OM' => '🇴🇲 Oman',

    'PK' => '🇵🇰 Pakistan',
    'PA' => '🇵🇦 Panama',
    'PG' => '🇵🇬 Papua New Guinea',
    'PY' => '🇵🇾 Paraguay',
    'PE' => '🇵🇪 Peru',
    'PH' => '🇵🇭 Philippines',
    'PL' => '🇵🇱 Poland',
    'PT' => '🇵🇹 Portugal',

    'QA' => '🇶🇦 Qatar',

    'RO' => '🇷🇴 Romania',
    'RU' => '🇷🇺 Russia',

    'SA' => '🇸🇦 Saudi Arabia',
    'RS' => '🇷🇸 Serbia',
    'SG' => '🇸🇬 Singapore',
    'SK' => '🇸🇰 Slovakia',
    'SI' => '🇸🇮 Slovenia',
    'ZA' => '🇿🇦 South Africa',
    'KR' => '🇰🇷 South Korea',
    'ES' => '🇪🇸 Spain',
    'SE' => '🇸🇪 Sweden',
    'CH' => '🇨🇭 Switzerland',

    'TH' => '🇹🇭 Thailand',
    'TN' => '🇹🇳 Tunisia',
    'TR' => '🇹🇷 Turkey',

    'UA' => '🇺🇦 Ukraine',
    'AE' => '🇦🇪 United Arab Emirates',
    'GB' => '🇬🇧 United Kingdom',
    'US' => '🇺🇸 United States',

    'UY' => '🇺🇾 Uruguay',

    'VN' => '🇻🇳 Vietnam',

    'ZM' => '🇿🇲 Zambia',
    'ZW' => '🇿🇼 Zimbabwe',
];